CLOCK						= "Clock";
BINDING_NAME_TOGGLECLOCK	= "Toggle Clock";
TIME_PLAYED_SESSION			= "Time played this session: %s"; -- The amount of time played this session
CLOCK_TIME_DAY				= "%d day";
CLOCK_TIME_HOUR				= "%d hour";
CLOCK_TIME_MINUTE			= "%d minute";
CLOCK_TIME_SECOND			= "%d second";
EXP_PER_HOUR_LEVEL			= "Experience per hour this level: %.2f";
EXP_PER_HOUR_SESSION		= "Experience per hour this session: %.2f";
EXP_TO_LEVEL				= "Experience to level: %d (%.2f%% to go)";
TIME_TO_LEVEL_LEVEL			= "Time to level at this level's rate: %s";
TIME_TO_LEVEL_SESSION		= "Time to level at this session's rate: %s";
TIME_INFINITE				= "infinite";
HEALTH_PER_SECOND			= "Health regenerated per second: %d";
MANA_PER_SECOND				= "Mana regenerated per second: %d";
NONCOMBAT_TRAVEL_PERCENTAGE	= "Time spent traveling this session: %.2f%%";
NONCOMBAT_TRAVEL_DISTANCE	= "Distance traveled this session: %.2f";
TRAVEL_SPEED				= "Travel speed as a percentage of run speed: %.2f%%"
